jobs:
  include:
    - language: python
      python: 3.8
      script:
        - python -c "print('Hi from Python!')"

    - language: node_js
      node_js: 13
      script:
        - node -e "console.log('Hi from NodeJS!')"
